export const APP_ROUTES = {
  home: "/",
  naTeiaDoBoato: {
    intro: "/na-teia-do-boato/introducao",
    "1": "/na-teia-do-boato/1",
    "1_1": "/na-teia-do-boato/1-1",
    "1_2": "/na-teia-do-boato/1-2",
    "2_1": "/na-teia-do-boato/2-1",
    "2_2": "/na-teia-do-boato/2-2",
    "2_3": "/na-teia-do-boato/2-3",
    "2_4": "/na-teia-do-boato/2-4",
    "3": "/na-teia-do-boato/3",
    final_1: "/na-teia-do-boato/4-final-1",
    final_2: "/na-teia-do-boato/4-final-2",
    final_3: "/na-teia-do-boato/4-final-3",
    final_4: "/na-teia-do-boato/4-final-4",
    final_5: "/na-teia-do-boato/4-final-5",
    final_6: "/na-teia-do-boato/4-final-6",
    final_7: "/na-teia-do-boato/4-final-7",
    final_8: "/na-teia-do-boato/4-final-8",
    conclusion: "/na-teia-do-boato/conclusao",
  },
};
